version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  advance:
    build: .
    ports:
      - "5000:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"